base_link:
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
link_1: 
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
link_2: 
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
imusensor:
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0

