controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
velocity_controllers:
  ros__parameters:
    joints: 
      - joint0
      - joint1
    command_interface: 
      - velocity
    state_interface: 
      - velocity
      - effort

# effort_controllers:
#   ros__parameters:
#     joints: 
#       - joint0
#     command_interface: 
#       - effort
#     state_interface: 
#       - position
#       - velocity
#       - effort